Freemius/wordpress-sdk

- config.php
- includes/fs-plugin-info-dialog.php
- templates/account.php
- templates/connect.php
- templates/debug.php
Hi,
I found time to fix some issues that Theme Check plugin raises when Freemius SDK is included in the theme. It is only the tip of the iceberg, but it is a start.
Usually `WP_DEBUG` constant can be used to achieve full reporting. Maybe I missed something?
`esc_attr_e` and `esc_html_e` are i18n functions merged with sanitization functions. If you're printing out a variable, the respective `esc_attr` and `esc_html` should be used (no `_e` at the end).
ASCII characters are safe in files. I changed the bullet char with the HTML entity `&bull;`.
---
Sharing my view on the rest of the errors:
- `WARNING: Found a translation function that is missing a text-domain.`
You will need to go through each of these and add text-domains.
- `WARNING: Found base64_encode in the file ...`
@vovafeldman …
> Fix some issues raised by Theme Check plugin

- includes/supplements/fs-essential-functions-1.1.7.1.php
The SDK path is incorrectly detected if there are any single-file-plugins that are listed earlier in the plugin list. Ignore single-file-plugins to fix this.
> Ignore single-file-plugins when finding the SDK location

- includes/class-fs-plugin-updater.php
There was a PHP warning after installing a plugin or theme by uploading a .zip
> [bug-fix] Php warning after plugin install

- includes/class-freemius.php
- start.php
Fixed an issue with the detection of the version of the theme that's being activated (free or premium)  which was preventing the skipping of the opt-in from working properly.
> [theme] [opt-in] Fixed an issue with theme activation.

- includes/managers/class-fs-option-manager.php
Problem
* Freemius re-sets an option named "fs_cache_843" on every request with an empty array, which causes the total cache of all options to be autoloaded to be regenerated on every single page view.
Cause
* The existing code tries to manage a cache for performance already, but it considers an existing empty array value to need updating. The default value is empty though.
Proposed solution
1. Only update the stored options if there no existing ones yet.
Notes
* Bugfix was originally filed against: https://github.com/fooplugins/foogallery/pull/152
> Fixed options manager cache causes rewrite of options cache on every request.

- includes/class-fs-logger.php
Unnecessary  optional arg ( all calls provide a value) on private function _log  line 145 of includes/class-fs-logger.php breaks PHP 8
> Fix for php8

- start.php
Plugin info can contain booleans and arrays too.
> fs_dynamic_init's paramter type fix

- includes/class-freemius.php
This prevents a fatal error when a user tries to activate the plugin and the SECURE_AUTH_KEY is missing in wp-config.php
> [bugfix] prevent fatal error on plugin activation when SECURE_AUTH_KEY is missing

- includes/managers/class-fs-key-value-storage.php
There are several "PHP Deprecated" warnings in the `FS_Key_Value_Storage` class due to incompatibility with the `ArrayAccess` interface. These warnings appeared as of PHP 8.1: https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/#php-8-1-return-type-enforcement-and-new-returntypewillchange-attribute
> [php8.1] Silence the deprecation notices introduced in PHP 8.1

- includes/class-freemius.php
- includes/entities/class-fs-affiliate-terms.php
- includes/i18n.php
- templates/forms/affiliation.php
Right now, we are sending affiliate requests to the main plugin installed through the bundle. Under the assumption that the developer would like to promote a Bundle when the `bundle_id` is set, we _should_ send the affiliate request to the bundle instead. This PR does that.
Additionally, I figured we could improve the application flow a little as we are already in the context.
---
When a plugin/theme user is applying to become an affiliate, if they haven't opted in, they we do opt them, but we do not track.
However, the opt-in process does require consent from the email sent. Due to this, when a non-opted user tries to submit the affiliate form, it fails and just returns a message saying "Account is pending activation".
From a user's perspective who hasn't opted in (skipped during plugin …
> Send Affiliate requests to the Bundle if the developer has used a bundle_id in dynamic_init

- includes/class-freemius.php
[filters] [new] Introduced `'checkout_url'` filter to optionally override the URL of the checkout across the entire SDK. And `'update_notice_checkout_url'` filter to specifically override the checkout URL shown in the admin notice when a license has expired.
> [filters] [new] Introduced `'checkout_url'` and `'update_notice_checkout_url'` as filters for the checkout URL.

- start.php
We use the internal SDK version as `2.5.4.2` and not `2.5.4` because in
one of the previous releases, we tagged it as `2.5.4.1` and it has been
out in the wild.
The next version would automatically simplify it.
> Prepare Release 2.5.4

- includes/class-freemius.php
- start.php
- templates/connect.php
> [license-activation] [links] Update Links in the Opt-In and License Activation UI

- includes/class-freemius.php
- start.php
We discovered an edge case in our SDK when a plugin's free and premium version needs to be running in parallel. In some cases, the updates from the premium version would show up under the Free version, causing confusion.
The SDK v2.5.12 fixes the issue.
> Deployment, Version 2.5.12

- includes/class-freemius.php
- includes/class-fs-garbage-collector.php
- start.php
Starting v2.6.2 we have enabled the garbage collector system by default. More information about it can be found [here](https://github.com/Freemius/wordpress-sdk/releases/tag/2.6.0).
If for some reason you want to explicitly disable it (for example, while you are developing something locally), you can do so by defining this constant in your `wp-config.php` file.
```php
// Disable Freemius WP-SDK Garbage Collector
if ( ! defined( 'WP_FS__ENABLE_GARBAGE_COLLECTOR' ) ) {
define( 'WP_FS__ENABLE_GARBAGE_COLLECTOR', false );
}
```
The Garbage Collector will run once every day and will clear data of any plugins/themes that have not been active for more than 1 week.
You can configure the expiration time with another constant:
```php
// Set expiration time to 30 days
if ( ! defined( …
```
> Version 2.6.2

- includes/fs-core-functions.php
> [wordpress-compliance] Fix the loading/enqueueing of JS scripts in WP.

- includes/entities/class-fs-site.php
Reference: [https://wiki.php.net/rfc/deprecate_dynamic_properties PHP RFC: Deprecate dynamic properties].
**How to Test.**
1. Ensure your WP instance is running on PHP 8.2+
2. Install Query Monitor with the latest SDK `develop` or `master` branch in use with any plugin. 
3. Change to the `feature/suppress-missing-dynamic-properties` branch
> [php82] Suppress PHP 8.2+ warnings for dynamic properties.

- includes/class-freemius.php
Fixes a bug where, if a license expires on a WordPress site and is subsequently renewed on the server side, the license expiration notice persists on the WordPress site even after the license details are synchronized with our server.
> [license] [sticky] [renewal] Remove sticky message on extended license

- languages/freemius.pot
- start.php
- templates/forms/subscription-cancellation.php
> [i18n] Update the strings for case sensitivity. Remove lines spacings in translatable strings.

- assets/scss/_mixins.scss
- assets/scss/admin/_ajax-loader.scss
- assets/scss/admin/_badge.scss
- assets/scss/admin/_modal-common.scss
- assets/scss/admin/_switch.scss
- assets/scss/admin/_tooltip.scss
- assets/scss/admin/add-ons.scss
- assets/scss/admin/affiliation.scss
- assets/scss/admin/common.scss
- assets/scss/admin/connect.scss
- assets/scss/customizer.scss
- start.php
> [cleanup] Remove unused mixins from the codebase

- includes/class-freemius.php
- includes/class-fs-logger.php
- includes/class-fs-storage.php
- includes/managers/class-fs-debug-manager.php
- require.php
- templates/debug.php
When the user activates debugging a single event cron starts:
`wp_schedule_single_event(time() + 24 * HOUR_IN_SECONDS, 'fs_debug_turn_off_logging_hook');`
When the user deactivates debuggong this cron is unscheduled:
`wp_unschedule_event($timestamp, 'fs_debug_turn_off_logging_hook');`
If the event happens, the option is set to off:
`add_action('fs_debug_turn_off_logging_hook', array( self::class, '_turn_off_debug_mode' ) );`
Also, in the debug page I added a countdown timer, so the user is informed about the fact that debugging will be disabled automatically.
> [debug] [logging] Automatically turn off `fs_debug_mode`after 24 hours

- assets/scss/admin/common.scss
Set z-index of `.fs-secure-notice` to 9989 in order to avoid covering `#adminmenuwrap` that has z-index: 9990
> Fix bug with notice bar covering menu

- includes/entities/class-fs-plugin-plan.php
- includes/entities/class-fs-site.php
- includes/entities/class-fs-user.php
- start.php
This is the correct PR, follow conversation on wrong PR here: https://github.com/Freemius/wordpress-sdk/pull/759
> Feature/daniele/fix deprecation warning with php8.2

- assets/scss/admin/common.scss
- includes/class-freemius.php
- start.php
Added a `display:flex` container to keep text and button separate and consistent in different screen sizes
> [trial] [dialog] Fixes trial activation button layout

- start.php
Changed `exit;` to `return;` in `start.php` to prevent the Freemius SDK from terminating execution in CLI environments where `ABSPATH` is not defined. This resolves conflicts with tools like PHPCS, PHPStan, and PHPUnit while ensuring the SDK remains functional within WordPress.
> Fix: Prevent SDK from exiting in CLI environments
